# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161021_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('storage3d', models.FileField(blank=True, null=True, upload_to='models3d/%Y-%m-%d')),
                ('texture3d', models.ImageField(blank=True, null=True, upload_to='models3d/%Y-%m-%d')),
                ('custom_model_js', models.FileField(blank=True, null=True, upload_to='models3d/each-js')),
                ('mesh_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh', to='shop.Product')),
            ],
        ),
    ]
