# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_3d', models.ImageField(blank=True, null=True, upload_to='models3d/%Y-%m-%d')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product3d')),
            ],
        ),
    ]
