# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160426_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='market',
        ),
    ]
