# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='market',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombra de tu tienda'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='historia'),
        ),
    ]
