# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_bio2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='Relata un poco sobre tu trabajo: cu\xe1nto tiempo llevas haci\xe9ndolo, c\xf3mo empez\xf3, d\xf3nde naci\xf3 tu creatividad, etc', max_length=200, null=True, verbose_name='Nuestra historia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='market',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre de tu tienda'),
        ),
    ]
