# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 06:00
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='add a valid URL', null=True, verbose_name='My video'),
        ),
    ]
