# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_profile_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='profile_background/%Y/%m/%d', verbose_name='Portada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('author',),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
    ]
