# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20160829_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background3',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='Portada_1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='Portada_2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='Portada_3'),
        ),
    ]
