# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20160829_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverpageprofile',
            name='author',
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='background_1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='background_2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background/%Y-%m-%d', verbose_name='background_3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='Relata un poco sobre tu trabajo: cu\xe1nto tiempo llevas haci\xe9ndolo, c\xf3mo empez\xf3, d\xf3nde naci\xf3 tu creatividad, etc', max_length=400, null=True, verbose_name='Our history'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='market',
            field=models.CharField(blank=True, max_length=30, verbose_name='Market'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='CoverPageProfile',
        ),
    ]
