# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 22:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_profile_fb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tw_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='facebook'),
        ),
    ]
