# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20160731_2007'),
        ('orders', '0023_auto_20160803_0244'),
    ]

    operations = [
    ]
