# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20160830_0836'),
        ('orders', '0039_auto_20161021_1758'),
    ]

    operations = [
    ]
