# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20161021_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='order',
            name='country_short',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='order',
            name='formatted_address',
            field=models.CharField(max_length=250, null=True, verbose_name='format Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='locality',
            field=models.CharField(max_length=100, null=True, verbose_name='locality'),
        ),
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='route'),
        ),
        migrations.AddField(
            model_name='order',
            name='sublocality',
            field=models.CharField(max_length=100, null=True, verbose_name='sublocality'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, null=True, verbose_name='postal code'),
        ),
    ]
