# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20161107_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='street number'),
        ),
    ]
