# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-07 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_order_street_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='state'),
        ),
    ]
