# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_merge'),
        ('orders', '0042_order_administrative_area_level_1'),
    ]

    operations = [
    ]
