# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order_administrative_area_level_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
