# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_merge'),
        ('orders', '0043_auto_20161210_2349'),
    ]

    operations = [
    ]
