# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, null=True, verbose_name='postal code'),
        ),
    ]
